version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - lll
    - mnd
    - nestif
    - nilerr
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen

  settings:
    funlen:
      lines: -1
      statements: 80 # default 40
    gocognit:
      min-complexity: 65 # default 30
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 30 # 30 by default (but we recommend 10-20)
    godox:
      keywords:
        - FIXME
    gosec:
      excludes:
        - G115 # integer overflow conversion
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US

  exclusions:
    warn-unused: true
    presets:
      - comments
    rules:
      - linters:
          - funlen
          - goconst
          - gosec
          - maintidx
        path: (.+)_test.go
      - linters:
          - forbidigo
        path: cmd/revgrep/main.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
