name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: stable
      GOLANGCI_LINT_VERSION: v2.0
      CGO_ENABLED: 0

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Test
        run: make test
